services:
  demos-db:
    image: postgres:16
    container_name: demos-db
    environment:
      POSTGRES_USER: profesor
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demos
    ports:
      - "5432:5432"          # cambia a "5433:5432" si ya usas 5432
    volumes:
      - demos-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U profesor -d demos"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    depends_on:
      demos-db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"            # acceder en http://localhost:8080
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  demos-data:
  pgadmin-data:
